name: wechat_camera_picker_demo
description: A new Flutter project.
version: 3.2.1+11
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  wechat_camera_picker:
    path: ../

flutter:
  uses-material-design: true
